<?php

declare(strict_types=1);

/**
 * Static vehicle catalog for the Version 1 public website.
 * @return list<array<string, mixed>>
 */
function vehicle_all(): array
{
    return [
        [
            "id" => 1,
            "slug" => "porsche-911",
            "name" => "Porsche 911 Carrera S",
            "brand" => "Porsche",
            "category" => "Luxury",
            "image" => "porsche-911.png",
            "price" => 35000,
            "seats" => 4,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 2,
            "slug" => "mclaren-720s",
            "name" => "McLaren 720S",
            "brand" => "McLaren",
            "category" => "Luxury",
            "image" => "mclaren-720s.png",
            "price" => 27000,
            "seats" => 2,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 3,
            "slug" => "rolls-royce-ghost",
            "name" => "Rolls-Royce Ghost",
            "brand" => "Rolls-Royce",
            "category" => "Luxury",
            "image" => "rolls-royce-ghost.png",
            "price" => 25000,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 4,
            "slug" => "lamborghini-urus",
            "name" => "Lamborghini Urus",
            "brand" => "Lamborghini",
            "category" => "Luxury",
            "image" => "lamborghini-urus.png",
            "price" => 20000,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 5,
            "slug" => "ferrari-roma",
            "name" => "Ferrari Roma",
            "brand" => "Ferrari",
            "category" => "Luxury",
            "image" => "ferrari-roma.png",
            "price" => 18000,
            "seats" => 4,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 6,
            "slug" => "ford-everest",
            "name" => "Ford Everest",
            "brand" => "Ford",
            "category" => "SUV",
            "image" => "ford-everest.png",
            "price" => 6500,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 7,
            "slug" => "nissan-terra",
            "name" => "Nissan Terra",
            "brand" => "Nissan",
            "category" => "SUV",
            "image" => "nissan-terra.png",
            "price" => 5500,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 8,
            "slug" => "mitsubishi-montero",
            "name" => "Mitsubishi Montero Sport",
            "brand" => "Mitsubishi",
            "category" => "SUV",
            "image" => "mitsubishi-montero.png",
            "price" => 5800,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 9,
            "slug" => "toyota-fortuner",
            "name" => "Toyota Fortuner",
            "brand" => "Toyota",
            "category" => "SUV",
            "image" => "toyota-fortuner.png",
            "price" => 6200,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 10,
            "slug" => "toyota-prado",
            "name" => "Toyota Land Cruiser Prado",
            "brand" => "Toyota",
            "category" => "SUV",
            "image" => "toyota-prado.png",
            "price" => 8500,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 11,
            "slug" => "nissan-navara",
            "name" => "Nissan Navara",
            "brand" => "Nissan",
            "category" => "Pickup",
            "image" => "nissan-navara.png",
            "price" => 3500,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 12,
            "slug" => "ford-ranger-raptor",
            "name" => "Ford Ranger Raptor",
            "brand" => "Ford",
            "category" => "Pickup",
            "image" => "ford-ranger-raptor.png",
            "price" => 5500,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 13,
            "slug" => "isuzu-dmax",
            "name" => "Isuzu D-Max",
            "brand" => "Isuzu",
            "category" => "Pickup",
            "image" => "isuzu-dmax.png",
            "price" => 3400,
            "seats" => 5,
            "transmission" => "Manual",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 14,
            "slug" => "toyota-hilux",
            "name" => "Toyota Hilux",
            "brand" => "Toyota",
            "category" => "Pickup",
            "image" => "toyota-hilux.png",
            "price" => 4500,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 15,
            "slug" => "toyota-hiace",
            "name" => "Toyota Hiace GL Grandia",
            "brand" => "Toyota",
            "category" => "Van",
            "image" => "toyota-hiace.png",
            "price" => 5500,
            "seats" => 10,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 16,
            "slug" => "tesla-model-3",
            "name" => "Tesla Model 3",
            "brand" => "Tesla",
            "category" => "EV",
            "image" => "tesla-model-3.png",
            "price" => 6500,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 17,
            "slug" => "mercedes-s-class",
            "name" => "Mercedes-Benz S-Class",
            "brand" => "Mercedes-Benz",
            "category" => "Luxury",
            "image" => "mercedes-s-class.png",
            "price" => 22000,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 18,
            "slug" => "bmw-7-series",
            "name" => "BMW 7 Series",
            "brand" => "BMW",
            "category" => "Luxury",
            "image" => "bmw-7-series.png",
            "price" => 21000,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 19,
            "slug" => "audi-a8",
            "name" => "Audi A8",
            "brand" => "Audi",
            "category" => "Luxury",
            "image" => "audi-a8.png",
            "price" => 19500,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 20,
            "slug" => "lexus-ls-500",
            "name" => "Lexus LS 500",
            "brand" => "Lexus",
            "category" => "Luxury",
            "image" => "lexus-ls-500.png",
            "price" => 18000,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 21,
            "slug" => "bentley-continental-gt",
            "name" => "Bentley Continental GT",
            "brand" => "Bentley",
            "category" => "Luxury",
            "image" => "bentley-continental-gt.png",
            "price" => 32000,
            "seats" => 4,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 22,
            "slug" => "maserati-quattroporte",
            "name" => "Maserati Quattroporte",
            "brand" => "Maserati",
            "category" => "Luxury",
            "image" => "maserati-quattroporte.png",
            "price" => 23000,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 23,
            "slug" => "porsche-panamera",
            "name" => "Porsche Panamera",
            "brand" => "Porsche",
            "category" => "Luxury",
            "image" => "porsche-panamera.png",
            "price" => 26000,
            "seats" => 4,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 24,
            "slug" => "jaguar-f-type",
            "name" => "Jaguar F-Type",
            "brand" => "Jaguar",
            "category" => "Luxury",
            "image" => "jaguar-f-type.png",
            "price" => 20500,
            "seats" => 2,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 25,
            "slug" => "bmw-m4-competition",
            "name" => "BMW M4 Competition",
            "brand" => "BMW",
            "category" => "Luxury",
            "image" => "bmw-m4-competition.png",
            "price" => 24000,
            "seats" => 4,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 26,
            "slug" => "mercedes-amg-gt",
            "name" => "Mercedes-AMG GT",
            "brand" => "Mercedes-Benz",
            "category" => "Luxury",
            "image" => "mercedes-amg-gt.png",
            "price" => 28500,
            "seats" => 2,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 27,
            "slug" => "toyota-land-cruiser-300",
            "name" => "Toyota Land Cruiser 300",
            "brand" => "Toyota",
            "category" => "SUV",
            "image" => "toyota-land-cruiser-300.png",
            "price" => 9800,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 28,
            "slug" => "nissan-patrol",
            "name" => "Nissan Patrol",
            "brand" => "Nissan",
            "category" => "SUV",
            "image" => "nissan-patrol.png",
            "price" => 9500,
            "seats" => 8,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 29,
            "slug" => "ford-territory",
            "name" => "Ford Territory",
            "brand" => "Ford",
            "category" => "SUV",
            "image" => "ford-territory.png",
            "price" => 4800,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 30,
            "slug" => "hyundai-palisade",
            "name" => "Hyundai Palisade",
            "brand" => "Hyundai",
            "category" => "SUV",
            "image" => "hyundai-palisade.png",
            "price" => 7200,
            "seats" => 8,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 31,
            "slug" => "kia-sorento",
            "name" => "Kia Sorento",
            "brand" => "Kia",
            "category" => "SUV",
            "image" => "kia-sorento.png",
            "price" => 6100,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 32,
            "slug" => "honda-cr-v",
            "name" => "Honda CR-V",
            "brand" => "Honda",
            "category" => "SUV",
            "image" => "honda-cr-v.png",
            "price" => 5200,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 33,
            "slug" => "mazda-cx-9",
            "name" => "Mazda CX-9",
            "brand" => "Mazda",
            "category" => "SUV",
            "image" => "mazda-cx-9.png",
            "price" => 6700,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 34,
            "slug" => "subaru-forester",
            "name" => "Subaru Forester",
            "brand" => "Subaru",
            "category" => "SUV",
            "image" => "subaru-forester.png",
            "price" => 5000,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 35,
            "slug" => "chevrolet-trailblazer",
            "name" => "Chevrolet Trailblazer",
            "brand" => "Chevrolet",
            "category" => "SUV",
            "image" => "chevrolet-trailblazer.png",
            "price" => 5700,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 36,
            "slug" => "suzuki-jimny",
            "name" => "Suzuki Jimny",
            "brand" => "Suzuki",
            "category" => "SUV",
            "image" => "suzuki-jimny.png",
            "price" => 3900,
            "seats" => 4,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 37,
            "slug" => "mitsubishi-triton",
            "name" => "Mitsubishi Triton",
            "brand" => "Mitsubishi",
            "category" => "Pickup",
            "image" => "mitsubishi-triton.png",
            "price" => 4300,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 38,
            "slug" => "mazda-bt-50",
            "name" => "Mazda BT-50",
            "brand" => "Mazda",
            "category" => "Pickup",
            "image" => "mazda-bt-50.png",
            "price" => 4400,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 39,
            "slug" => "chevrolet-colorado",
            "name" => "Chevrolet Colorado",
            "brand" => "Chevrolet",
            "category" => "Pickup",
            "image" => "chevrolet-colorado.png",
            "price" => 4600,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 40,
            "slug" => "nissan-frontier-pro-4x",
            "name" => "Nissan Frontier Pro-4X",
            "brand" => "Nissan",
            "category" => "Pickup",
            "image" => "nissan-frontier-pro-4x.png",
            "price" => 5200,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 41,
            "slug" => "ford-ranger-wildtrak",
            "name" => "Ford Ranger Wildtrak",
            "brand" => "Ford",
            "category" => "Pickup",
            "image" => "ford-ranger-wildtrak.png",
            "price" => 4900,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 42,
            "slug" => "toyota-hilux-gr-sport",
            "name" => "Toyota Hilux GR Sport",
            "brand" => "Toyota",
            "category" => "Pickup",
            "image" => "toyota-hilux-gr-sport.png",
            "price" => 5400,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 43,
            "slug" => "isuzu-dmax-x-terrain",
            "name" => "Isuzu D-Max X-Terrain",
            "brand" => "Isuzu",
            "category" => "Pickup",
            "image" => "isuzu-dmax-x-terrain.png",
            "price" => 5000,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 44,
            "slug" => "mitsubishi-strada-athlete",
            "name" => "Mitsubishi Strada Athlete",
            "brand" => "Mitsubishi",
            "category" => "Pickup",
            "image" => "mitsubishi-strada-athlete.png",
            "price" => 4700,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 45,
            "slug" => "jac-t9",
            "name" => "JAC T9",
            "brand" => "JAC",
            "category" => "Pickup",
            "image" => "jac-t9.png",
            "price" => 3900,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 46,
            "slug" => "foton-thunder",
            "name" => "Foton Thunder",
            "brand" => "Foton",
            "category" => "Pickup",
            "image" => "foton-thunder.png",
            "price" => 3600,
            "seats" => 5,
            "transmission" => "Manual",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 47,
            "slug" => "ram-1500",
            "name" => "RAM 1500",
            "brand" => "RAM",
            "category" => "Pickup",
            "image" => "ram-1500.png",
            "price" => 7200,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Gasoline",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 48,
            "slug" => "hyundai-staria",
            "name" => "Hyundai Staria",
            "brand" => "Hyundai",
            "category" => "Van",
            "image" => "hyundai-staria.png",
            "price" => 6800,
            "seats" => 11,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 49,
            "slug" => "toyota-hiace-commuter",
            "name" => "Toyota Hiace Commuter",
            "brand" => "Toyota",
            "category" => "Van",
            "image" => "toyota-hiace-commuter.png",
            "price" => 5900,
            "seats" => 15,
            "transmission" => "Manual",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 50,
            "slug" => "nissan-urvan-premium",
            "name" => "Nissan Urvan Premium",
            "brand" => "Nissan",
            "category" => "Van",
            "image" => "nissan-urvan-premium.png",
            "price" => 5700,
            "seats" => 15,
            "transmission" => "Manual",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 51,
            "slug" => "kia-carnival",
            "name" => "Kia Carnival",
            "brand" => "Kia",
            "category" => "Van",
            "image" => "kia-carnival.png",
            "price" => 7000,
            "seats" => 8,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 52,
            "slug" => "maxus-g10",
            "name" => "Maxus G10",
            "brand" => "Maxus",
            "category" => "Van",
            "image" => "maxus-g10.png",
            "price" => 5100,
            "seats" => 9,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 53,
            "slug" => "foton-toano",
            "name" => "Foton Toano",
            "brand" => "Foton",
            "category" => "Van",
            "image" => "foton-toano.png",
            "price" => 5300,
            "seats" => 15,
            "transmission" => "Manual",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 54,
            "slug" => "mercedes-v-class",
            "name" => "Mercedes-Benz V-Class",
            "brand" => "Mercedes-Benz",
            "category" => "Van",
            "image" => "mercedes-v-class.png",
            "price" => 12000,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 55,
            "slug" => "volkswagen-multivan",
            "name" => "Volkswagen Multivan",
            "brand" => "Volkswagen",
            "category" => "Van",
            "image" => "volkswagen-multivan.png",
            "price" => 8500,
            "seats" => 7,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 56,
            "slug" => "peugeot-traveller",
            "name" => "Peugeot Traveller",
            "brand" => "Peugeot",
            "category" => "Van",
            "image" => "peugeot-traveller.png",
            "price" => 7600,
            "seats" => 8,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 57,
            "slug" => "hyundai-h100",
            "name" => "Hyundai H-100",
            "brand" => "Hyundai",
            "category" => "Van",
            "image" => "hyundai-h100.png",
            "price" => 4200,
            "seats" => 12,
            "transmission" => "Manual",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 58,
            "slug" => "maxus-v80",
            "name" => "Maxus V80",
            "brand" => "Maxus",
            "category" => "Van",
            "image" => "maxus-v80.png",
            "price" => 4800,
            "seats" => 12,
            "transmission" => "Manual",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 59,
            "slug" => "ford-transit",
            "name" => "Ford Transit",
            "brand" => "Ford",
            "category" => "Van",
            "image" => "ford-transit.png",
            "price" => 6100,
            "seats" => 15,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 60,
            "slug" => "renault-trafic",
            "name" => "Renault Trafic",
            "brand" => "Renault",
            "category" => "Van",
            "image" => "renault-trafic.png",
            "price" => 6500,
            "seats" => 9,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 61,
            "slug" => "mercedes-sprinter",
            "name" => "Mercedes-Benz Sprinter",
            "brand" => "Mercedes-Benz",
            "category" => "Van",
            "image" => "mercedes-sprinter.png",
            "price" => 9800,
            "seats" => 15,
            "transmission" => "Automatic",
            "fuel" => "Diesel",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 62,
            "slug" => "hyundai-ioniq-5",
            "name" => "Hyundai Ioniq 5",
            "brand" => "Hyundai",
            "category" => "EV",
            "image" => "hyundai-ioniq-5.png",
            "price" => 7200,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 63,
            "slug" => "kia-ev6",
            "name" => "Kia EV6",
            "brand" => "Kia",
            "category" => "EV",
            "image" => "kia-ev6.png",
            "price" => 7400,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 64,
            "slug" => "byd-atto-3",
            "name" => "BYD Atto 3",
            "brand" => "BYD",
            "category" => "EV",
            "image" => "byd-atto-3.png",
            "price" => 5600,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 65,
            "slug" => "nissan-leaf",
            "name" => "Nissan Leaf",
            "brand" => "Nissan",
            "category" => "EV",
            "image" => "nissan-leaf.png",
            "price" => 4800,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 66,
            "slug" => "bmw-i4",
            "name" => "BMW i4",
            "brand" => "BMW",
            "category" => "EV",
            "image" => "bmw-i4.png",
            "price" => 10500,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 67,
            "slug" => "mercedes-eqe",
            "name" => "Mercedes-Benz EQE",
            "brand" => "Mercedes-Benz",
            "category" => "EV",
            "image" => "mercedes-eqe.png",
            "price" => 11800,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 68,
            "slug" => "porsche-taycan",
            "name" => "Porsche Taycan",
            "brand" => "Porsche",
            "category" => "EV",
            "image" => "porsche-taycan.png",
            "price" => 17000,
            "seats" => 4,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 69,
            "slug" => "audi-e-tron-gt",
            "name" => "Audi e-tron GT",
            "brand" => "Audi",
            "category" => "EV",
            "image" => "audi-e-tron-gt.png",
            "price" => 15500,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 70,
            "slug" => "volvo-ex30",
            "name" => "Volvo EX30",
            "brand" => "Volvo",
            "category" => "EV",
            "image" => "volvo-ex30.png",
            "price" => 6800,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 71,
            "slug" => "mg4-ev",
            "name" => "MG4 EV",
            "brand" => "MG4",
            "category" => "EV",
            "image" => "mg4-ev.png",
            "price" => 5200,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 72,
            "slug" => "honda-cr-v-hybrid",
            "name" => "Honda CR-V Hybrid",
            "brand" => "Honda",
            "category" => "EV",
            "image" => "honda-cr-v-hybrid.png",
            "price" => 5900,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Hybrid",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 73,
            "slug" => "toyota-corolla-cross-hybrid",
            "name" => "Toyota Corolla Cross Hybrid",
            "brand" => "Toyota",
            "category" => "EV",
            "image" => "toyota-corolla-cross-hybrid.png",
            "price" => 5700,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Hybrid",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 74,
            "slug" => "tesla-model-y",
            "name" => "Tesla Model Y",
            "brand" => "Tesla",
            "category" => "EV",
            "image" => "tesla-model-y.png",
            "price" => 7800,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
        [
            "id" => 75,
            "slug" => "byd-seal",
            "name" => "BYD Seal",
            "brand" => "BYD",
            "category" => "EV",
            "image" => "byd-seal.png",
            "price" => 6900,
            "seats" => 5,
            "transmission" => "Automatic",
            "fuel" => "Electric",
            "created_at" => "2026-09-01 11:31:54",
        ],
    ];
}
